LOGO_ROWS           equ 18
LOGO_COLS           equ 64
LOGO_COLS_PER_BLOCK equ 16

LOGO_TOP_MARGIN     equ (TEXT_ROWS - LOGO_ROWS) / 2
LOGO_LEFT_MARGIN    equ (TEXT_COLS - LOGO_COLS) / 2
LOGO_RIGHT_MARGIN   equ TEXT_COLS - LOGO_LEFT_MARGIN - LOGO_COLS
