TEXT_COLS       equ 80
TEXT_ROWS       equ 25
TEXT_CHARSIZE   equ 2

BLACK           equ 0x0
DARK_BLUE       equ 0x1
DARK_GREEN      equ 0x2
DARK_CYAN       equ 0x3
DARK_RED        equ 0x4
DARK_MAGENTA    equ 0x5
BROWN           equ 0x6
LIGHT_GREY      equ 0x7
DARK_GREY       equ 0x8
LIGHT_BLUE      equ 0x9
LIGHT_GREEN     equ 0xa
LIGHT_CYAN      equ 0xb
LIGHT_RED       equ 0xc
LIGHT_MAGENTA   equ 0xd
YELLOW          equ 0xe
WHITE           equ 0xf
